// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumw7ng_x6o0v3RlxhBxyrGgTIit5kMAk',
    appId: '1:639156209644:web:f43d7acaa73c9997b262c9',
    messagingSenderId: '639156209644',
    projectId: 'flutblog',
    authDomain: 'flutblog.firebaseapp.com',
    storageBucket: 'flutblog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDssRu7IyCFPCApKOTHooSpkc_m1CcvaX0',
    appId: '1:639156209644:android:bda9ba72e446932bb262c9',
    messagingSenderId: '639156209644',
    projectId: 'flutblog',
    storageBucket: 'flutblog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmabu3KtfTHQE7Uzm_PZjs3G7dhCOV3f0',
    appId: '1:639156209644:ios:0afd6866ec91df2ab262c9',
    messagingSenderId: '639156209644',
    projectId: 'flutblog',
    storageBucket: 'flutblog.appspot.com',
    iosBundleId: 'com.example.flutBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmabu3KtfTHQE7Uzm_PZjs3G7dhCOV3f0',
    appId: '1:639156209644:ios:098408217da53dbdb262c9',
    messagingSenderId: '639156209644',
    projectId: 'flutblog',
    storageBucket: 'flutblog.appspot.com',
    iosBundleId: 'com.example.flutBlog.RunnerTests',
  );
}
